### ISSUE TITLE
missing script: bendystraw

### ISSUE THREAD

**Issue by dylanspurgin** [brousalis/bendystraw#1]
Apologize if I'm missing something obvious. After doing the following from the root of my project

```
npm install --save-dev bendystraw
```
Then
```
npm run bendystraw
```
I get 
> npm ERR! missing script: bendystraw

**Comment by brousalis** [comment]
you aren't! very sorry, I've been actively working on this and didn't know anyone else found it. 

that command is not be working, i'll make sure to update the readme with the latest changes I've made. 

for now, you could copy the `gulpfile.js` folder into your root from bendystraw, or create a file in your root called `gulpfile.js` and put:
    require('bendystraw');

I'm hoping to have some time very soon to add overrides for the options (some paths are hard coded. check out the [example](https://github.com/brousalis/bendystraw/tree/example) to see how I setup an app using it). 

sorry for all the confusion!
